### ISSUE TITLE
Error when trying to download default model.

### ISSUE THREAD

**Issue by mchataway** [Bismuth-Consultancy-BV/MLOPs#114]
Hi there, I have been following the install instructions youtube video posted a month ago, and everything is working smoothly up until the step to click the "Download Model" shelf button.
When I do this, I get the following output in the console:

```
Traceback (most recent call last):
  File "E:\resources/houdini/plugins/MLOPs/scripts/python\mlops_utils.py", line 318, in on_accept
    ensure_huggingface_model_local(model_name, download_dir)
  File "E:\resources/houdini/plugins/MLOPs/scripts/python\mlops_utils.py", line 209, in ensure_huggingface_model_local
    from diffusers import StableDiffusionPipeline
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\accelerate\accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\accelerate\utils\__init__.py", line 116, in <module>
    from .megatron_lm import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Program Files\Side Effects Software\Houdini 19.5.682\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "E:\resources\houdini\plugins\MLOPs\data\dependencies\python\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

I have checked and I don't have another PYTHONPATH environment variable set in the Windows system.
I am using Windows 10, Houdini 19.5.682

Any guidance would be great.. thanks!

**Comment by brendaneddy** [comment]
Same Issue on Houdini 19.5.605 and 19.5.303

**Comment by Ambrosiussen** [comment]
Hi, update MLOPs and reinstall dependencies. I believe this is fixed!

**Comment by mchataway** [comment]
Thanks Paul, it's working now!
