### ISSUE TITLE
Issue when using most of MLOPS nodes

### ISSUE THREAD

**Issue by Leemboo** [Bismuth-Consultancy-BV/MLOPs#115]
Hello there,

I am getting the below error message when using most of MLOPS nodes.

```
Traceback (most recent call last):
  File "/obj/geo1/sd_pipeline1/sd_scheduler1/scheduler", line 2, in expression
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/RenderNode/Documents/GitHub/MLOPs/scripts/python\sdpipeline\schedulers_lookup.py", line 1, in <module>
    from diffusers import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\diffusers\utils\accelerate_utils.py", line 20, in <module>
    from .import_utils import is_accelerate_available
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\diffusers\utils\import_utils.py", line 222, in <module>
    import torch
  File "C:\Program Files\Side Effects Software\Houdini 19.5.640.3.9\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\RenderNode\Documents\GitHub\MLOPs\data\dependencies\python\torch\__init__.py", line 457, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined
```
Any sort of help would be much appreciated. I am running Houdini 19.5.640 (Python 3.9).

Thanks!

**Comment by Ambrosiussen** [comment]
Hi, this issue has been fixed for H20 in the 3.0 release!
