### ISSUE TITLE
MLOPs 3.0 install issue with H20.0.625 - No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by AM-FX** [Bismuth-Consultancy-BV/MLOPs#144]
Probably a beginner's question: When installing MLOPS3 and Houdini 20.0.625 a long error message regarding Numpy appears. `"Original error was: No module named 'numpy.core._multiarray_umath'"`
This was an update from MLOPS2 to MLOPS3 via Github Desktop Pull and the video tutorial for MLOPS2. The path of in MLOPs.json was changed accordingly: "MLOPS": "X:/GitHub_Repositories/MLOPs/"

What else I tried:
- I installed the specified NumPy version 1.24.4, then realized that this should already be included in the dependencies of the repository. 
- The houdini.env file does not point to other Python or NumPy versions.
- Without MLOPS.json Houdini starts normally

```
verrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\utils.py", line 32, in register_pyhandle
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\Houdini\HOUDIN~1.625\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/viewer_handles\sidefx_hud_slider.py", line 12, in <module>
    import viewerhandle.hudutils as hudut
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\hudutils.py", line 3, in <module>
    import resourceui as rui
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\resourceui.py", line 5, in <module>
    import numpy
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Program Files\Houdini\Houdini20.0.625\bin\houdini.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


ERROR: C:/PROGRA~1/Houdini/HOUDIN~1.625/houdini/viewer_handles/sidefx_hud_toggle.py
Traceback (most recent call last):
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\utils.py", line 32, in register_pyhandle
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\Houdini\HOUDIN~1.625\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/viewer_handles\sidefx_hud_toggle.py", line 11, in <module>
    import viewerhandle.hudutils as hudut
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\hudutils.py", line 3, in <module>
    import resourceui as rui
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\resourceui.py", line 5, in <module>
    import numpy
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Program Files\Houdini\Houdini20.0.625\bin\houdini.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


ERROR: C:/PROGRA~1/Houdini/HOUDIN~1.625/houdini/viewer_handles/sidefx_hud_trackpad.py
Traceback (most recent call last):
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\utils.py", line 32, in register_pyhandle
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\Houdini\HOUDIN~1.625\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/viewer_handles\sidefx_hud_trackpad.py", line 12, in <module>
    import viewerhandle.hudutils as hudut
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\viewerhandle\hudutils.py", line 3, in <module>
    import resourceui as rui
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/Houdini/HOUDIN~1.625/houdini/python3.10libs\resourceui.py", line 5, in <module>
    import numpy
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Program Files\Houdini\Houdini20.0.625\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "X:\GitHub_Repositories\MLOPs\data\dependencies\python\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Program Files\Houdini\Houdini20.0.625\bin\houdini.exe"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by AM-FX** [comment]
Issue resolved: cloning the rep again after deleting it completely fixed the issue
