### ISSUE TITLE
SDXL implementation not working

### ISSUE THREAD

**Issue by mnlrbr** [Bismuth-Consultancy-BV/MLOPs#145]
I tried the "experimental.hip" file in the repositorz and it was stuck on the tokenizer.
The following message appeared:

after download and test, the error was the following
Error 
Invalid source /obj/geo1/sdsolver1/solver.
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 60, in <module>
File "D:\Github/MLOPS2/scripts/python\sdpipeline\default_pipeline.py", line 203, in run
output_image = pipe(
File "D:\Github\MLOPS_2\data\dependencies\python\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "D:\Github\MLOPS_2\data\dependencies\python\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 832, in __call
noise_pred = self.unet(
File "D:\Github\MLOPS_2\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(args, **kwargs)
File "D:\Github\MLOPS_2\data\dependencies\python\accelerate\hooks.py", line 165, in new_forward
output = module._old_forward(args, kwargs)
File "D:\Github\MLOPS_2\data\dependencies\python\diffusers\models\unet_2d_condition.py", line 889, in forward
aug_emb = self.add_embedding(add_embeds)
File "D:\Github\MLOPS_2\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, kwargs)
File "D:\Github\MLOPS_2\data\dependencies\python\diffusers\models\embeddings.py", line 192, in forward
sample = self.linear_1(sample)
File "D:\Github\MLOPS_2\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "D:\Github\MLOPS_2\data\dependencies\python\torch\nn\modules\linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x60672 and 2816x1280)
). 

It would be nice to understand how does on change and use the different models on Hugging face. I wasn't sure to have downloaded the right SDXL model.

Cheers

**Comment by olop2** [comment]
Hi , look [here](https://github.com/Bismuth-Consultancy-BV/MLOPs/issues/142) maybe the steps i explained will work for you
