### ISSUE TITLE
Error installing dependencies in Houdini 20.5

### ISSUE THREAD

**Issue by mrgbell** [Bismuth-Consultancy-BV/MLOPs#152]
When installing a fresh copy of MLOPs in **Houdini Core 20.5.278 - Py3.11** on Windows 10, I am running into the following error: 
**ERROR: Invalid requirement: 'alphapose==0.5.0-': Expected end or semicolon (after version specifier)**

I checked that PYTHONPATH is not defined in the system environment variables. In Houdini's About menu I see the value of PYTHONPATH as:

`PYTHONPATH                             E:/MLOPs/scripts/python/characterpipeline/MotionBert;E:/MLOPs/data/dependencies/python`

I tried reinstalling in Houdini 20.0.751 - Py3.10 and run into the same error

```

Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "E:\MLOPs/scripts/python\mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "E:\MLOPs/scripts/python\mlops_utils.py", line 433, in pip_install
    raise hou.Error(res[1].decode())
hou.Error: E:\MLOPs\data\dependencies\python\_distutils_hack\__init__.py:32: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
ERROR: Invalid requirement: 'alphapose==0.5.0-': Expected end or semicolon (after version specifier)
    alphapose==0.5.0-
             ~~~~~~~^ (from line 69 of E:/MLOPs/requirements.txt)


```
![image](https://github.com/user-attachments/assets/9a19e32e-6b96-403e-a4bb-4219fd6593cb)

**Comment by mansvr** [comment]
having the same issue. any solutions?

**Comment by mrgbell** [comment]
Afraid not. I have given up on it for the moment

**Comment by mansvr** [comment]
ty for the response. will wait for the update.

**Comment by Ambrosiussen** [comment]
Hi this should be fixed! :) Can you try latest?
