### ISSUE TITLE
Problem installing MLOPS Dependencies with H20.5

### ISSUE THREAD

**Issue by cityshake** [Bismuth-Consultancy-BV/MLOPs#155]
I get this error message when installing MLOPS with 20.5.278. Anyone has a solution? Thank you.

![image](https://github.com/user-attachments/assets/74717f83-b569-44f6-b8a6-8c38b5f34e4b)

Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "C:\Users/Utilisateur/Documents/houdini_assets/MLOPS/scripts/python\mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True, constraints_file=hou.text.expandString("$MLOPS/constraints.txt"))
  File "C:\Users/Utilisateur/Documents/houdini_assets/MLOPS/scripts/python\mlops_utils.py", line 433, in pip_install
    raise hou.Error(res[1].decode())
hou.Error:   error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      [Redshift] Redshift for Houdini plugin version 3.6.4 (Jul 17 2024 10:59:13)
      [Redshift] Plugin compile time HDK version: 20.5.278
      [Redshift] Houdini host version: 20.5.278
      [Redshift] Plugin dso/dll and config path: C:/ProgramData/Redshift/Plugins/Houdini/20.5.278/dso
      [Redshift] Core data path: C:\ProgramData\Redshift
      [Redshift] Local data path: C:\ProgramData\Redshift
      [Redshift] Procedurals path: C:\ProgramData\Redshift\Procedurals
      [Redshift] Preferences file path: C:\ProgramData\Redshift\preferences.xml
      [Redshift] License path: C:\ProgramData\Redshift
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-311\psutil
      creating build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [Redshift] Closing the RS instance. End of the plugin log system.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psutil)

**Comment by RyanAnimation** [comment]
I don't have redshift installed and I'm having the same thing. I install this in Houdini 20.5.

**Comment by RyanAnimation** [comment]
I get it solved after I install the visual studio with c++ build tool

**Comment by ForteDexe** [comment]
`cent call last):
  File "mlops_install", line 5, in <module>
  File "path/MLOPs-main/scripts/python\mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True, constraints_file=hou.text.expandString("$MLOPS/constraints.txt"))
  File "path/MLOPs-main/scripts/python\mlops_utils.py", line 433, in pip_install
    raise hou.Error(res[1].decode())
hou.Error: \\virtuosgames.com\SPX\LIBRARY\FX\00_PRO_HOUDINI\00_HOUDINI_ENVIROMENT_SETUP\MLOPs-main\data\dependencies\python\_distutils_hack\__init__.py:32: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-311\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-311\psutil
      creating build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-311\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\psutil
      creating build\temp.win-amd64-cpython-311\Release\psutil\arch
      creating build\temp.win-amd64-cpython-311\Release\psutil\arch\windows
      "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -IC:\PROGRA~1\SIDEEF~1\HOUDIN~1.278\python311\include -IC:\PROGRA~1\SIDEEF~1\HOUDIN~1.278\python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-cpython-311\Release\psutil/_psutil_common.obj
      _psutil_common.c
      C:\Program Files\Side Effects Software\Houdini 20.5.278\python311\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]`
      
I installed vs with c++ but still fail ....

**Comment by czetan** [comment]
> I get it solved after I install the visual studio with c++ build tool

Yes, that helped. I got them from here:
https://visualstudio.microsoft.com/downloads/?q=build+tools
