### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

### ISSUE THREAD

**Issue by akre54** [Bismuth-Consultancy-BV/MLOPs#26]
Hi there, great package. I'm really enjoying it so far.

I'm getting this error on the `sd_solver` node with controlnet.

Both my `sd_latent_noise_generate` and `sd_image_to_points` nodes are set to 512x512. The conditioning seems to be irrelevant as does the controlnet model. Skipping controlnet and using the image as an input for the scheduler's latents works as expected.

Happy to upload the hip if it helps.

Windows 10, Houdini 19.5

```
Invalid source [/obj/geo1/sd_solver1/solver](node:/obj/geo1/sd_solver1/solver)
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 46, in <module>
File "C:/Users/adam.krebs/Houdini Packages/MLOPs-main/scripts/python\sdpipeline\image_solve.py", line 72, in run
down_block_res_samples, mid_block_res_sample = controlnet(latent_model_input, t.to(torch.float16), encoder_hidden_states=text_embeddings, controlnet_cond=controlnet_conditioning_image, conditioning_scale=controlnet_scale, return_dict=False,)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_controlnet.py", line 134, in forward
return_dict,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\controlnet.py", line 529, in forward
cross_attention_kwargs=cross_attention_kwargs,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\unet_2d_blocks.py", line 870, in forward
cross_attention_kwargs=cross_attention_kwargs,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\transformer_2d.py", line 270, in forward
class_labels=class_labels,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\attention.py", line 316, in forward
**cross_attention_kwargs,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\attention_processor.py", line 248, in forward
**cross_attention_kwargs,
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\diffusers\models\attention_processor.py", line 375, in __call__
key = attn.to_k(encoder_hidden_states)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "C:/Users/ADAM~1.KRE/Dropbox/PC(2)~1/DOCUME~1/houdini19.5/scripts/python\torch\nn\modules\linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
.
```

Any advice? Thanks!

**Comment by akre54** [comment]
[mlops controlnet error.zip](https://github.com/Bismuth-Consultancy-BV/MLOPs/files/11334926/mlops.controlnet.error.zip)

**Comment by Ambrosiussen** [comment]
What is your MLOPS_MODEL set to? For ControlNet it needs to be 1.5, eg: runwayml/stable-diffusion-v1-5

Check out the example file > controlnet! :)

**Comment by akre54** [comment]
Ah, I'm just going off of [Mo's youtube video](https://www.youtube.com/watch?v=_bxir7qGjzQ) which showed it using $MLOPS_MODEL. I didn't change anything about the default models.

```
    MLOPS                                  C:/Users/adam.krebs/Houdini Packages/MLOPs-main
    MLOPS_MODEL                            C:/Users/adam.krebs/Houdini Packages/MLOPs-main/checkpoints/stabilityai-_-stable-diffusion-2-1
    MLOPS_MODELS                           C:/Users/adam.krebs/Houdini Packages/MLOPs-main/checkpoints
```

If I change the Unet Model, Scheduler Model and ControlNet model to runwayml/stable-diffusion-v1-5, I get:

```
OSError: Error no file named config.json found in directory C:/Users/adam.krebs/Houdini Packages/MLOPs-main/checkpoints/runwayml-_-stable-diffusion-v1-5.
```

Here's the directory listing:
```
C:\Users\adam.krebs\Houdini Packages\MLOPs-main\checkpoints\runwayml-_-stable-diffusion-v1-5>dir
 Volume in drive C is OS
 Volume Serial Number is ###

 Directory of C:\Users\adam.krebs\Houdini Packages\MLOPs-main\checkpoints\runwayml-_-stable-diffusion-v1-5

04/26/2023  01:14 PM    <DIR>          .
04/26/2023  01:14 PM    <DIR>          ..
04/26/2023  01:14 PM    <DIR>          feature_extractor
04/26/2023  01:14 PM               543 model_index.json
04/26/2023  01:14 PM    <DIR>          safety_checker
04/26/2023  01:14 PM    <DIR>          scheduler
04/26/2023  01:14 PM    <DIR>          text_encoder
04/26/2023  01:14 PM    <DIR>          tokenizer
04/26/2023  01:14 PM    <DIR>          unet
04/26/2023  01:14 PM    <DIR>          vae
```

**Comment by akre54** [comment]
FWIW I was able to run the example file and use the Multi_ControlNet example, but every time I change an input it opens the "Fetching 15 files" dialog

**Comment by Ambrosiussen** [comment]
Is this still unresolved? If so please re-open.

**Comment by akre54** [comment]
I'm still seeing it, but I ended up just forking the example per your advice. Thanks
