### ISSUE TITLE
No module named 'huggingface_hub

### ISSUE THREAD

**Issue by Luo-qiulin** [Bismuth-Consultancy-BV/MLOPs#32]
```
Traceback (most recent call last):
  File "D:\MLOPs-main/scripts/python\mlops_utils.py", line 77, in on_accept
    ensure_huggingface_model_local(model_name, download_dir)
  File "D:\MLOPs-main/scripts/python\mlops_utils.py", line 34, in ensure_huggingface_model_local
    from huggingface_hub import snapshot_download
  File "C:\Program Files\Side Effects Software\Houdini 19.5.569\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'huggingface_hub'
```
after the install Dependences, I click the Download Model button, it raises this error.what's the problem?

**Comment by Ambrosiussen** [comment]
Did you restart Houdini after installing dependencies?

**Comment by Luo-qiulin** [comment]
yes restarted servel times

**Comment by Luo-qiulin** [comment]
please tell me where is the module "huggingface_hub" file, I will check if it is exist。

**Comment by DarkOakSoftware** [comment]
probably related to: #27

disable RM/Octane as a work around by moving the appropriate json file out of /packages

**Comment by Luo-qiulin** [comment]
I have cleaned the HOUDINI_USER_PREF_DIR and even the temp cache files.then reinstalled dependencies. the same problem still here.

**Comment by Luo-qiulin** [comment]
```
bin
filelock
filelock-3.9.0.dist-info
functorch
isympy.py
jinja2
Jinja2-3.1.2.dist-info
markupsafe
MarkupSafe-2.1.2.dist-info
mpmath
mpmath-1.2.1.dist-info
networkx
networkx-3.0.dist-info
nvfuser
share
sympy
sympy-1.11.1.dist-info
torch
torch-2.0.0+cu117.dist-info
torchgen
typing_extensions-4.4.0.dist-info
typing_extensions.py
__pycache__
```
that's all dependencies in my Documents\houdini19.5\scripts\python,is it enough?

**Comment by AntimodularResearch** [comment]
I ran into this issue and solved it by installing Python 3.9.13 and then installing the hugging_hub, diffusers and torch modules.
I disabled Renderman momentarily since there seems to be some conflict there. After everything works, you can re-enable it.
Using Windows 11 and Houdini 19.5.569

**Comment by felipemeres** [comment]
'huggingface_hub' is not there - and there are many other dependencies missing as well if you pasted the entire contents of the folder. try reinstalling from the toolbar and keep an eye on the log to see if you're getting any install error that is preventing dependencies from being installed

**Comment by Ambrosiussen** [comment]
Make sure you have no other packages installed for Houdini while installing dependencies. Those can cause conflicts in PATH while installing.

**Comment by Luo-qiulin** [comment]
```
1. accelerate
2. accelerate-0.18.0.dist-info
3. aiohttp
4. aiohttp-3.8.4.dist-info
5. aiosignal
6. aiosignal-1.3.1.dist-info
7. antlr4
8. antlr4_python3_runtime-4.9.3.dist-info
9. async_timeout
10. async_timeout-4.0.2.dist-info
11. attr
12. attrs
13. attrs-23.1.0.dist-info
14. bin
15. certifi
16. certifi-2022.12.7.dist-info
17. CHANGELOG.md
18. charset_normalizer
19. charset_normalizer-3.1.0.dist-info
20. clip_interrogator
21. clip_interrogator-0.6.0.dist-info
22. colorama
23. colorama-0.4.6.dist-info
24. controlnet_aux
25. controlnet_aux-0.0.3.dist-info
26. cv2
27. diffusers
28. diffusers-0.15.0.dist-info
29. einops
30. einops-0.6.1.dist-info
31. filelock
32. filelock-3.12.0.dist-info
33. filelock-3.9.0.dist-info
34. frozenlist
35. frozenlist-1.3.3.dist-info
36. fsspec
37. fsspec-2023.4.0.dist-info
38. ftfy
39. ftfy-6.1.1.dist-info
40. functorch
41. google
42. huggingface_hub
43. huggingface_hub-0.14.1.dist-info
44. idna
45. idna-3.4.dist-info
46. imageio
47. imageio-2.28.0.dist-info
48. importlib_metadata
49. importlib_metadata-6.6.0.dist-info
50. isympy.py
51. jinja2
52. Jinja2-3.1.2.dist-info
53. lazy_loader
54. lazy_loader-0.2.dist-info
55. markupsafe
56. MarkupSafe-2.1.2.dist-info
57. mpmath
58. mpmath-1.2.1.dist-info
59. mpmath-1.3.0.dist-info
60. multidict
61. multidict-6.0.4.dist-info
62. networkx
63. networkx-3.0.dist-info
64. networkx-3.1.dist-info
65. numpy
66. numpy-1.24.3.dist-info
67. nvfuser
68. omegaconf
69. omegaconf-2.3.0.dist-info
70. openai
71. openai-0.27.5.dist-info
72. opencv_contrib_python-4.7.0.72.dist-info
73. opencv_python-4.7.0.72.dist-info
74. open_clip
75. open_clip_torch-2.18.0.dist-info
76. packaging
77. packaging-23.1.dist-info
78. PIL
79. Pillow-9.5.0.dist-info
80. protobuf-3.20.3-py3.9-nspkg.pth
81. protobuf-3.20.3.dist-info
82. psutil
83. psutil-5.9.5.dist-info
84. pydevd_plugins
85. PyWavelets-1.4.1.dist-info
86. pywt
87. PyYAML-6.0.dist-info
88. README.md
89. regex
90. regex-2023.3.23.dist-info
91. requests
92. requests-2.29.0.dist-info
93. safetensors
94. safetensors-0.3.1.dist-info
95. scikit_image-0.20.0.dist-info
96. scipy
97. scipy-1.10.1-cp39-cp39-win_amd64.whl
98. scipy-1.10.1.dist-info
99. scipy-1.9.1.dist-info
100. scipy.libs
101. sentencepiece
102. sentencepiece-0.1.98.dist-info
103. share
104. skimage
105. sympy
106. sympy-1.11.1.dist-info
107. tifffile
108. tifffile-2023.4.12.dist-info
109. timm
110. timm-0.6.13.dist-info
111. tokenizers
112. tokenizers-0.13.3.dist-info
113. torch
114. torch-2.0.0+cu117.dist-info
115. torch-2.0.0.dist-info
116. torchgen
117. torchmetrics
118. torchmetrics-0.11.4.dist-info
119. torchvision
120. torchvision-0.15.1.dist-info
121. tqdm
122. tqdm-4.65.0.dist-info
123. training
124. transformers
125. transformers-4.28.1.dist-info
126. typing_extensions-4.4.0.dist-info
127. typing_extensions-4.5.0.dist-info
128. typing_extensions.py
129. urllib3
130. urllib3-1.26.15.dist-info
131. wcwidth
132. wcwidth-0.2.6.dist-info
133. yaml
134. yarl
135. yarl-1.9.2.dist-info
136. zipp
137. zipp-3.15.0.dist-info
138. _yaml
139. __pycache__
```
oh i lost so many dependencies! after manually pip installed throse packaegs list in 'install dependencies', it works propertly.
I guess the problem is the subprocesses have not finilished yet, some subprocess called 'sucessfull' message out .

**Comment by Ambrosiussen** [comment]
Im moving all dependencies into requirements.txt to make it easier.
