### ISSUE TITLE
Problem with the sd_tokenizer node.

### ISSUE THREAD

**Issue by ASunren** [Bismuth-Consultancy-BV/MLOPs#61]
Error 
Invalid source /obj/box_object1/sd_tokenizer1/tokenizer
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Program Files\Side Effects Software\Houdini 19.5.605\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "C:\AlexDocuments/houdini19.5/MLOPs-main/scripts/python\sdpipeline\tokenizer.py", line 1, in <module>
from transformers import CLIPTokenizer
File "C:\Program Files\Side Effects Software\Houdini 19.5.605\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'transformers'
.

**Comment by Ambrosiussen** [comment]
Hi, did you install the dependencies with the shelf tool?

**Comment by ASunren** [comment]
Hi, yes i installed the dependencies with the shelf tool, but the error remains. I think that error with paths.

**Comment by ASunren** [comment]
![Untitled-1](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/20853631/39a5d300-e622-40a7-972f-6c0b4d11ff84)

**Comment by ASunren** [comment]
![Untitled-2](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/20853631/9d2edf3e-254a-4152-b23b-4fc46eaea896)

**Comment by ASunren** [comment]
This is installed libraries.
![Untitled-3](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/20853631/6acb673d-bfda-4194-ad8e-2ed6a5987c5a)

**Comment by ASunren** [comment]
![Untitled-4](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/20853631/35058414-66c4-481d-a3bf-13919736e2b6)


Traceback (most recent call last):
  File "C:\AlexDocuments/houdini19.5/MLOPs-main/scripts/python\mlops_utils.py", line 120, in on_accept
    ensure_huggingface_model_local(model_name, download_dir)
  File "C:\AlexDocuments/houdini19.5/MLOPs-main/scripts/python\mlops_utils.py", line 39, in ensure_huggingface_model_local
    from huggingface_hub import snapshot_download
  File "C:\Program Files\Side Effects Software\Houdini 19.5.605\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensuppor
t\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'huggingface_hub'

**Comment by Ambrosiussen** [comment]
And just to be sure... You get this error after restarting Houdini?

**Comment by ASunren** [comment]
Yes.

**Comment by Ambrosiussen** [comment]
Hi, I have reworked this logic a bit. Could you try the lora_training branch of MLOPs? (Install from scratch)

**Comment by ASunren** [comment]
Thank you very much!👍🙋🏻‍♂️😀
