### ISSUE TITLE
Nodes fail to cook after interrupting process

### ISSUE THREAD

**Issue by petebrooks** [Bismuth-Consultancy-BV/MLOPs#63]
If I need to cancel a process by hitting esc, many nodes display the error "Cooking was interrupted". After this happens it is impossible to get them to cook again. I have tried changing the display flag, changing the noise seed, replacing the noise generate node, changing the frame, toggling auto update, forcing update with OD tools re-cook node menu action, etc. The only thing that fixes the problem is quitting Houdini and starting a new session. It would save a lot of frustration if this worked correctly, as it's easy to inadvertently kick off a slow process.

<img width="638" alt="image" src="https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7389762/d88f19a1-d07c-4d89-b7a4-59c664f0708e">

![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7389762/3d2921ef-7b3c-4584-be1f-42c1944c0aa4)

```
Traceback (most recent call last):
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\nodegraph.py", line 166, in handleEventCoroutine
    event_handler = event_handler.handleEvent(uievent,
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\nodegraph.py", line 1208, in handleEvent
    return handler.handleEvent(uievent, pending_actions)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\nodegraph.py", line 1039, in handleEvent
    view.modifySelection(uievent, None, itemset, self.item,
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\nodegraphview.py", line 271, in modifySelection
    editor.setCurrentNode(current, False)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\houpythonportion\ui.py", line 1119, in decorator
    return func(*args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.9libs\hou.py", line 22797, in setCurrentNode
    return _hou.PathBasedPaneTab_setCurrentNode(self, node, pick_node)
hou.OperationInterrupted: The requested operation was interrupted.
Traceback (most recent call last):
  File "Mouse Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Mouse Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Timer Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Mouse Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Mouse Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Network Editor Left Title", line 1, in <module>
OSError: Signal 2 ignored due to race condition
Traceback (most recent call last):
  File "Mouse Event Handler", line 1, in <module>
OSError: Signal 2 ignored due to race condition
```

**Comment by Ambrosiussen** [comment]
Unfortunately this is a Houdini issue, and not an issue I can fix myself. I agree though its very frustrating
