### ISSUE TITLE
mlops 2.0 - sd pipeline node error

### ISSUE THREAD

**Issue by HubertPokrandt** [Bismuth-Consultancy-BV/MLOPs#95]
Ive got this:

Error 
Invalid source /obj/geo1/sd_pipeline1/sd_text_encoder1/text_encoder
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 25, in <module>
File "C:\github/MLOPS/scripts/python\sdpipeline\text_encoder.py", line 28, in run
text_encoder.to(torch_device)
File "C:\github\MLOPS\data\dependencies\python\transformers\modeling_utils.py", line 1878, in to
return super().to(*args, **kwargs)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1145, in to
return self._apply(convert)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 797, in _apply
module._apply(fn)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 797, in _apply
module._apply(fn)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 797, in _apply
module._apply(fn)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 820, in _apply
param_applied = fn(param)
File "C:\github\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1143, in convert
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
File "C:\github\MLOPS\data\dependencies\python\torch\cuda\__init__.py", line 247, in _lazy_init
torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
.
Unable to cook the test input.

**Comment by HubertPokrandt** [comment]
Hi, 

Do I need Nvidia card for running mlops ?

**Comment by melMass** [comment]
> RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Do you have up to date NVIDIA drivers and CUDA installed?

**Comment by HubertPokrandt** [comment]
Hello ,

I have AMD Radeon

Regards

czw., 8 cze 2023, 16:58 użytkownik Mel Massadian ***@***.***>
napisał:

**Comment by melMass** [comment]
As is MLOPS currently only works with Nvidia GPU (CUDA) or Apple Metal (MPS).
There is a [beta AMD (ROCM) version of pytorch](https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/) but currently this is not handled and I'm not sure of the issues that could arise from it

**Comment by melMass** [comment]
Yes I was referring to the "accelerated" options, but CPU should work, do you also have errors on CPU?
Inference is quite fast, but there is still extra time consumed for other stuff (quite hard to solve in Houdini).
